koxudaxi/local-data-api

- local_data_api/main.py
- local_data_api/models.py
- tests/test_main.py
I have implemented the logic for blobValue
https://github.com/koxudaxi/local-data-api/issues/1
> support blobValue

- .travis.yml
- requirements.txt
- upgrade fastapi to 0.30.0
- upgrade pydantic to 0.28
> Upgrade fastapi

- local_data_api/main.py
- local_data_api/models.py
- tests/test_models.py
- fix to execute with parameters (include batch)
- fix close and commit control
> fix to execute with parameters

- Dockerfile
- docker-compose.yml
- local_data_api/__init__.py
- local_data_api/exceptions.py
- local_data_api/main.py
- local_data_api/models.py
- local_data_api/resources/__init__.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/mysql.py
- local_data_api/resources/mysql.py
- local_data_api/resources/resource.py
- local_data_api/resources/sqlite.py
- local_data_api/secret_manager.py
- local_data_api/settings.py
- requirements.txt
- tests/test_exceptions.py
- tests/test_functions.py
- tests/test_models.py
- tests/test_resource/jdbc/test_jdbc.py
- tests/test_resource/jdbc/test_mysql.py
- tests/test_resource/test_mysql.py
- tests/test_resource/test_resource.py
- tests/test_secret_manager.py
- tests/test_settings.py
I think DataAPI uses JDBC drivers for accessing a database.
I create this pull request to support to get column metadata from MySQL.
https://github.com/koxudaxi/local-data-api/pull/11
> support JDBC Drivers

- .travis.yml
- local_data_api/main.py
- local_data_api/models.py
- requirements.txt
- tests/test_main.py
- add unittest for main
- fix rollback message
> add unittest for main

- .travis.yml
- Dockerfile
- local_data_api/__init__.py
- local_data_api/main.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/mysql.py
- local_data_api/resources/mysql.py
- local_data_api/resources/resource.py
- local_data_api/resources/sqlite.py
- local_data_api/secret_manager.py
- local_data_api/settings.py
- requirements-test.txt
- requirements.txt
- scripts/push-image.sh
- setup.cfg
- setup.py
- tests/test_functions.py
- tests/test_main.py
- tests/test_models.py
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_mysql.py
- tests/test_resource/test_mysql.py
- tests/test_resource/test_resource.py
- tests/test_secret_manager.py
- tests/test_settings.py
chanage flake8 to black
change nosetest to pytest
add isort
> change development tools

- docker-compose.yml
- local_data_api/main.py
- local_data_api/models.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/resource.py
- tests/test_resource/test_jdbc/test_jdbc.py
IncludeResultMetadata is broken.
The PR fixes to return ResultMetadata to a client.
> Fix includeResultMetadata

- Dockerfile
- README.md
The PR update MySQL client version for JDBC
> update mysql client

- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/mysql.py
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_mysql.py
The PR fixes auto-commit  on jdbc
> Fix autocommit on jdbc

- Dockerfile
- README.md
- docker-compose-mysql.yml
- docker-compose-postgres.yml
- local_data_api/resources/__init__.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/postgres.py
- local_data_api/resources/resource.py
- local_data_api/settings.py
- scripts/format.sh
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_postgres.py
- tests/test_settings.py
Now, local-data-api supports PostgreSQL
https://github.com/koxudaxi/local-data-api/issues/27
> support postgresql

- local_data_api/main.py
- local_data_api/models.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/mysql.py
- local_data_api/resources/resource.py
- local_data_api/resources/sqlite.py
- tests/test_main.py
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_mysql.py
- tests/test_resource/test_jdbc/test_postgres.py
- tests/test_resource/test_mysql.py
- tests/test_resource/test_resource.py
This PR fixes a bug that the app can't change the database for Postgres.
https://github.com/koxudaxi/local-data-api/issues/44
> fix target database

- local_data_api/main.py
This PR fix begin-transaction bug.
> Fix begin-transaction bug

- local_data_api/settings.py
This PR fix settings.py for using pymysql.
https://github.com/koxudaxi/local-data-api/issues/50
> fix settings.py for pymysql

- local_data_api/models.py
- tests/test_models.py
Hello!
Just created also the issue ;).
First PR here in github ;)!
Issue here https://github.com/koxudaxi/local-data-api/issues/53
> #53 Support BigInt columns

- local_data_api/main.py
- local_data_api/models.py
- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/mysql.py
- local_data_api/resources/jdbc/postgres.py
- local_data_api/resources/mysql.py
- local_data_api/resources/resource.py
- local_data_api/resources/sqlite.py
- local_data_api/settings.py
- mypy.ini
- pyproject.toml
- scripts/format.sh
- scripts/lint.sh
- tests/test_main.py
- tests/test_models.py
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_mysql.py
- tests/test_resource/test_jdbc/test_postgres.py
- tests/test_resource/test_resource.py
- tests/test_secret_manager.py
This PR moves tools settings to pyproject.toml
> move tools setting to pyproject.toml

- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/mysql.py
- local_data_api/resources/postgres.py
- local_data_api/resources/resource.py
- local_data_api/resources/sqlite.py
- tests/test_resource/test_jdbc/test_jdbc.py
- tests/test_resource/test_jdbc/test_mysql.py
- tests/test_resource/test_jdbc/test_postgres.py
- tests/test_resource/test_mysql.py
- tests/test_resource/test_resource.py
This PR improves ColumnMetaData
https://github.com/koxudaxi/local-data-api/issues/50
> improve columnMetaData

- local_data_api/resources/resource.py
This PR fixes an error edge case when we use MySQL JDBC Driver
https://github.com/koxudaxi/local-data-api/issues/60
> Fix mysqljdbc edge case

- local_data_api/models.py
- tests/test_models.py
Just created the issue #62 , this pr also closes #36 (and the implementation don't follow the current aurora data api).
Like I write in the issue it only works on PostgreSQLJDBC since making a conversion for list type is dangerous (maybe in a further refactor).
> Support PgArray columns

- README.md
https://github.com/koxudaxi/local-data-api/issues/74
> update readme for PostgreSQL

- local_data_api/resources/jdbc/postgres.py
- local_data_api/resources/resource.py
- tests/test_resource/test_jdbc/test_postgres.py
- tests/test_resource/test_resource.py
https://github.com/koxudaxi/local-data-api/issues/79
> support postgresql geometric

- local_data_api/models.py
- tests/test_models.py
All parameters with the Null field set to False would have 'false' as a value.
> Fix Null field being set to false setting the value to False.

- local_data_api/resources/jdbc/__init__.py
- scripts/integration-test.sh
> Add support for binary types

- local_data_api/resources/jdbc/__init__.py
- local_data_api/resources/jdbc/mysql.py
- local_data_api/resources/jdbc/postgres.py
- scripts/integration-test.sh
https://github.com/koxudaxi/local-data-api/issues/90
> Fix timestamp bug on jaydebeapi

- local_data_api/resources/jdbc/__init__.py
- scripts/integration-test.sh
- tests/test_resource/test_jdbc/test_jdbc.py
https://github.com/koxudaxi/local-data-api/issues/90
> Fix null on jdbc

- kotlin/local-data-api/src/com/koxudaxi/localDataApi/Application.kt
- kotlin/local-data-api/src/com/koxudaxi/localDataApi/LocalDataApi.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/LocalDataApiTest.kt
https://github.com/koxudaxi/local-data-api/issues/106
> Fix alter error

- kotlin/local-data-api/src/com/koxudaxi/localDataApi/Application.kt
- kotlin/local-data-api/src/com/koxudaxi/localDataApi/LocalDataApi.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/ApplicationTest.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/LocalDataApiTest.kt
https://github.com/koxudaxi/local-data-api/issues/106#issuecomment-802238420
> Fix getGeneratedKeys

- kotlin/local-data-api/src/com/koxudaxi/localDataApi/LocalDataApi.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/LocalDataApiTest.kt
https://github.com/koxudaxi/local-data-api/issues/112
> Fix timestamptz offset

- kotlin/local-data-api/src/com/koxudaxi/localDataApi/LocalDataApi.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/ApplicationTest.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/LocalDataApiTest.kt
https://github.com/koxudaxi/local-data-api/issues/112
> Fix timetz offset

- kotlin/local-data-api/build.gradle
- kotlin/local-data-api/src/com/koxudaxi/localDataApi/Application.kt
- kotlin/local-data-api/src/com/koxudaxi/localDataApi/LocalDataApi.kt
- kotlin/local-data-api/src/com/koxudaxi/localDataApi/Models.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/ApplicationTest.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/ModelsTest.kt
- https://github.com/koxudaxi/local-data-api/issues/128
- https://github.com/koxudaxi/local-data-api/issues/125
- https://github.com/koxudaxi/local-data-api/issues/119
> Support array

- kotlin/local-data-api/src/com/koxudaxi/localDataApi/Resource.kt
- kotlin/local-data-api/test/com/koxudaxi/localDataApi/ApplicationTest.kt
https://github.com/koxudaxi/local-data-api/issues/117
> Support Java SDK

- README.md
https://github.com/koxudaxi/local-data-api/issues/128
> Add document to insert array data

- kotlin/local-data-api/Dockerfile
https://github.com/koxudaxi/local-data-api/issues/133
> Expose port 80
